AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'npapim2'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'none'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
